version: "3.8"

services:
  database:
    image: "postgres"    
    volumes:
      - database-data:/var/lib/postgresql/data/    
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
volumes:
  database-data: